
trigger:
  branches:
    include:
    - topic/arm64-ci

pool:
  vmImage: 'Windows-latest'

variables:
- template: vars/vars-all.yaml

steps:
- template: steps/git-checkout.yaml
- template: steps/build.yaml
- template: steps/publish.yaml
