steps:
  - task: MSBuild@1
    displayName: Restore nuget packages and generate credential templates
    inputs:
      solution: '$(Solution.SourceDirectory)/$(Solution.SourceProject).sln'
      platform: $(Solution.Platform)
      configuration: 'Release'
      msbuildArguments: '/restore /t:PrepareForBuild'

  - task: MSBuild@1
    displayName: Build and package
    inputs:
      solution: '$(Solution.SourceDirectory)/$(Solution.SourceProject).sln'
      platform: $(Solution.Platform)
      configuration: 'Release'
