steps:
  - task: MSBuild@1
    displayName: Build and package
    inputs:
      solution: '$(Solution.SourceDirectory)/$(Solution.SourceProject).sln'
      platform: $(Solution.Platform)
      configuration: 'Release'
